iname: CI Unit Tests

on:
  push:
    branches: ["*"]

jobs:
  unit-tests:
    name: Unit tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Show Python version
        run: python --version

      - name: Run unit tests
        run: python -m unittest discover -v
